server:
  port: 8000

spring:
  application:
    name: nova-invest-backend
  data:
    mongodb:
      uri: ${MONGO_URL}
      database: ${DB_NAME}
  jackson:
    property-naming-strategy: SNAKE_CASE
app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-hours: 12
    refresh-token-days: 7
  frontend-url: ${FRONTEND_URL}
  brevo:
    api-key: ${BREVO_EMAIL_KEY}
  base-url: ${APP_BASE_URL:http://localhost:8000/api/auth}
  admin:
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}
  wallets:
    btc: ${BTC_WALLET:bc1q96ge9unzzumwv2amfx3g9u26v8xpxp77sg0755}
    eth: ${ETH_WALLET:0x1f55B93eFe09b82C166c811e1241309B319CA70c}
    usdt: ${USDT_WALLET:TUfv1Xf7tdZvMeqjzRy3GnwHDqSxYLyAoe }

logging:
  level:
    com.novainvest: INFO